### ISSUE TITLE
Merge "Score Correction Guidelines" Google Doc into this repo's file curation guidelines.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/standards#51]
The [Score Correction Guidelines](https://docs.google.com/document/d/1Q2svEUSsE7OCetik8An__gsEwQCYNfFJlHFMF9dRce4/edit) Google Doc should be merged with the File Curation guidelines contains in this website. Creating new scores and cleaning up existing scores are different processes but their outcome should be the same: a DCML-compliant score.

We should have a dedicated docs webpage on "DCML-compliant score specs" and link to that page from wherever necessary (including the pipeline docs).

This will reduce maintenance effort, simplify the work of engravers/curators, and inform testing of our MEI/MuseScore converter.

**Comment by johentsch** [comment]
#52 has integrated the mentioned gDoc in the documentation as https://dcmlab.github.io/standards/build/html/scores/guidelines.html 

**ToDo**

- [ ] restructure so that the guidelines work for both newly typeset scores and correcting existing scores
- [ ] adapt and merge https://dcmlab.github.io/standards/build/html/pipeline/pipeline.html#file-curation
- [ ] make sure it mentions, wherever necessary, how something is done in MuseScore (3)
- [ ] (feel free to add)
